Revert "Feat/#33 drawing gesture of egg"
DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg pull request #49
Opened 2023-07-22 18:13 UTC by SeBin-Kwon

Reverts DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#42

2023-07-22 18:37 UTC, SeBin-Kwon commented
0. 마지막 커밋 푸쉬 후 프로젝트 파일 충돌로 머지를 시도함
<img width="742" alt="스크린샷 2023-07-23 오전 3 15 06" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/c21e94e7-3b27-4e67-80a6-5df89ad6e842">

1. 먼저 dev로 브랜치 바꿔서 최신 dev로 업데이트 해줬음

<img width="707" alt="스크린샷 2023-07-23 오전 3 17 04" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/f284116b-736a-40be-95c3-fae129d1e5c0">

2. 이후 Feat/#33 브랜치로 변경 후 merge를 시도함. 그런데 충돌없이 그냥 바로 merge됨.

<img width="607" alt="스크린샷 2023-07-23 오전 3 20 53" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/9a96fe6f-bffb-4dfc-b129-910de0f23adc">

3. vscode 열어보니 내가 쓴 코드와 차차 코드가 잘 merge 된 것 같음. 그런데 귀신같이 없어야할 EggInterationStores.swift가 살아나있음.

![스크린샷 2023-07-23 오전 3 24 10](https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/f38fe9e8-7ff6-40c4-ace2-20d6a3df03dc)

4. xcode를 열어보니 개같이 내 파일 없어져있음. 그런데 내 로컬 폴더나 vscode는 멀쩡함. 그래서 xcode만 문젠가?싶었음

5. xcode 오지게 껐다 켜고 뭘해도 안되길래 일단 merge 커밋이 올라가 있으니깐 push 해봄

![스크린샷 2023-07-23 오전 3 28 45](https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/c78aa649-4328-4b98-a598-322ef3fcb8b7)

6. github의 풀리퀘에서는 충돌이 안나서 머지풀리퀘버튼이 생겼고 file changed 부분을 봐도 잘 반영이 되어있음을 확인함.

7. 잘은 모르겠지만... 그냥 내 xcode가 이상한걸까.. 잘된것 같은데.. 머지해도 리벌트로 돌리면 되지 않을까.. 해서 머지풀리퀘를 누름

8. 깃허브로 봤을 땐 dev에 성공적으로 머지된 것 처럼 보였음

<img width="500" alt="스크린샷 2023-07-23 오전 3 33 52" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/50bcb09a-bed8-48a1-871e-578c0c90599e">

9. 그런데 암만 풀 땡겨도 내 xcode에 반영이 전혀 안됨.

<img width="578" alt="스크린샷 2023-07-23 오전 3 36 10" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/95c0c090-7e97-4d53-b5aa-aa78df38b5b7">

10. 그래서 다른 폴더에 클론을 받아봤더니

<img width="346" alt="스크린샷 2023-07-23 오전 3 36 36" src="https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/f7d08a50-ee8c-4295-b52c-052ce993a604">

11. 짜잔~ 하.....

2023-07-23 04:24 UTC, ValseLee commented
1. xcode 내의 폴더 트리에서 빨갛게 되어 있는 파일은 '삭제'되었다기보다 Xcode가 '신경쓰지 않는다' 는 의미에 가깝슴다
2. 애초에 삭제되면 폴더 트리에 안떠요!
3. 아마 pbxproj 파일이 머지되면서 비니의 파일을 올바른 Compile Source Folder로 넣지 않은 것 같습니다
4. Finder에는 파일이 있는걸 보니, Xcode 내에서 빨간 파일들을 삭제해주고, Finder의 파일들을 넣어주면 될 것으로 보입니다

불안하면 월요일에 진행 같이 고고

2023-07-23 04:24 UTC, ValseLee requested changes
우선 조치 사항을 커멘트로 적어두었으니, Merge는 잠시 기다려봅시당

2023-07-23 05:21 UTC, SeBin-Kwon commented
![스크린샷 2023-07-23 오후 2 16 27](https://github.com/DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg/assets/102914072/bc005a11-9b8f-40ac-947b-2f617a37dd83)

해결해서 revert 없이 그냥 클로즈함

2023-07-23 05:21 UTC, closed without merging